# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/z00a/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/z00a/proprietary/etc/catalog/V1_7260/audiocomms_config/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml:system/etc/catalog/V1_7260/audiocomms_config/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml \
    vendor/asus/z00a/proprietary/etc/catalog/V1_7260/audiocomms_config/parameter-framework/Settings/Route/RouteConfigurableDomains.xml:system/etc/catalog/V1_7260/audiocomms_config/parameter-framework/Settings/Route/RouteConfigurableDomains.xml \
    vendor/asus/z00a/proprietary/etc/catalog/V1_DSDA/audiocomms_config/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml:system/etc/catalog/V1_DSDA/audiocomms_config/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml \
    vendor/asus/z00a/proprietary/etc/catalog/V1_DSDA/audiocomms_config/parameter-framework/Settings/Route/RouteConfigurableDomains.xml:system/etc/catalog/V1_DSDA/audiocomms_config/parameter-framework/Settings/Route/RouteConfigurableDomains.xml \
    vendor/asus/z00a/proprietary/etc/firmware/BCM4335C0_003.001.009.0105.0563_Asus_ZE551ML.hcd:system/etc/firmware/BCM4335C0_003.001.009.0105.0563_Asus_ZE551ML.hcd \
    vendor/asus/z00a/proprietary/etc/atomisp/00t4k37.aiqb:system/etc/atomisp/00t4k37.aiqb \
    vendor/asus/z00a/proprietary/etc/DataSet/ispDB/ParameterDB.db:system/etc/DataSet/ispDB/ParameterDB.db \
    vendor/asus/z00a/proprietary/etc/DataSet/ispDB/ParameterDB.db:system/etc/DataSet/ispDB/ParameterDB.db \
    vendor/asus/z00a/proprietary/lib/DataSet/ditSCidGen/msgchk.db:system/lib/DataSet/ditSCidGen/msgchk.db \
    vendor/asus/z00a/proprietary/lib/DIT_AT_BACK_HL.cfg:system/lib/DIT_AT_BACK_HL.cfg \
    vendor/asus/z00a/proprietary/lib/DIT_AT_BACK_NORMAL.cfg:system/lib/DIT_AT_BACK_NORMAL.cfg \
    vendor/asus/z00a/proprietary/lib/DIT_AT_BACK_SR.cfg:system/lib/DIT_AT_BACK_SR.cfg \
    vendor/asus/z00a/proprietary/lib/hw/camera.mofd_v1.so:system/lib/hw/camera.mofd_v1.so \
    vendor/asus/z00a/proprietary/lib/hw/m10mo/camera.m10mo.so:system/lib/hw/m10mo/camera.m10mo.so \
    vendor/asus/z00a/proprietary/lib/libxditk_AT.so:system/lib/libxditk_AT.so \
    vendor/asus/z00a/proprietary/lib/libxditk_DIT_Moorefield.so:system/lib/libxditk_DIT_Moorefield.so \
    vendor/asus/z00a/proprietary/lib/libxditk_ISP.so:system/lib/libxditk_ISP.so \
    vendor/asus/z00a/proprietary/etc/firmware/FW_INFO.bin:system/etc/firmware/FW_INFO.bin \
    vendor/asus/z00a/proprietary/etc/firmware/M10MO_fw.bin:system/etc/firmware/M10MO_fw.bin \
    vendor/asus/z00a/proprietary/vendor/firmware/bcm2079x-a2_firmware.ncd:system/vendor/firmware/bcm2079x-a2_firmware.ncd \
    vendor/asus/z00a/proprietary/lib/librapid-ril-core.so:system/lib/librapid-ril-core.so \
    vendor/asus/z00a/proprietary/vendor/firmware/telephony/hash:system/vendor/firmware/telephony/hash \
    vendor/asus/z00a/proprietary/vendor/firmware/telephony/XMM_7260_REV20_1524.00_V4.0_ASUS7262_HSIC_FLASHLESS.fls:system/vendor/firmware/telephony/XMM_7260_REV20_1524.00_V4.0_ASUS7262_HSIC_FLASHLESS.fls \
    vendor/asus/z00a/proprietary/etc/firmware/psh.bin:system/etc/firmware/psh.bin
